version: "3.8"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  backend:
    build: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    build: frontend
    #image: ef01b7aff8b31d1f64bb7998db2780ec4f300a679731d67dffa3d07ef713a4fe
    command: npm run serve
    volumes:
      - ./frontend/brapifront:/app
      #- /app/node_modules
    #hot reload
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "8080:8080"
