# Generated by Django 3.1.4 on 2020-12-18 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('cropDbId', models.TextField(primary_key=True, serialize=False, verbose_name=' cropDbId')),
                ('commonName', models.TextField(verbose_name=' commonName')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contactDbId', models.TextField(primary_key=True, serialize=False, verbose_name=' contactDbId')),
                ('name', models.TextField(blank=True, verbose_name=' name')),
                ('email', models.TextField(blank=True, verbose_name=' email')),
                ('type', models.TextField(blank=True, verbose_name=' type')),
                ('orcid', models.TextField(blank=True, verbose_name=' orcid')),
                ('instituteName', models.TextField(blank=True, verbose_name=' instituteName')),
                ('cropDbId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brapp.crop', verbose_name=' cropDbId')),
            ],
        ),
    ]
